-- Generated by Tools/UpdateStatGoals.ps1.
-- Source data: direct Archon PvE pages and direct Murlok PvP pages.
-- Re-run the updater instead of editing this file by hand.

ZoidsToolsStatGoals = ZoidsToolsStatGoals or {}
ZoidsToolsStatGoals.generatedAt = "2026-06-28 13:26:23 -05:00"
ZoidsToolsStatGoals.data = {
    ["DEATHKNIGHT"] = {
        ["blood"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 544, haste = 438, mastery = 821, versatility = 709 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/raid/overview/mythic/all-bosses", targets = { crit = 822, haste = 910, mastery = 653, versatility = 208 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/death-knight/blood/3v3", targets = { crit = 35, haste = 766, mastery = 310, versatility = 861 } },
        },
        ["frost"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1029, haste = 364, mastery = 1157, versatility = 64 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/raid/overview/mythic/all-bosses", targets = { crit = 1015, haste = 358, mastery = 1192, versatility = 66 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/death-knight/frost/3v3", targets = { crit = 132, haste = 242, mastery = 758, versatility = 798 } },
        },
        ["unholy"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1121, haste = 290, mastery = 1186, versatility = 52 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/raid/overview/mythic/all-bosses", targets = { crit = 1043, haste = 349, mastery = 1161, versatility = 62 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/death-knight/unholy/3v3", targets = { crit = 42, haste = 321, mastery = 619, versatility = 957 } },
        },
    },
    ["DEMONHUNTER"] = {
        ["devourer"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 284, haste = 1137, mastery = 1227, versatility = 50 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/raid/overview/mythic/all-bosses", targets = { crit = 289, haste = 1102, mastery = 1213, versatility = 61 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/demon-hunter/devourer/3v3", targets = { crit = 40, haste = 452, mastery = 889, versatility = 515 } },
        },
        ["havoc"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1239, haste = 240, mastery = 1061, versatility = 64 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/raid/overview/mythic/all-bosses", targets = { crit = 1192, haste = 315, mastery = 1007, versatility = 76 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/demon-hunter/havoc/3v3", targets = { crit = 10, haste = 285, mastery = 872, versatility = 729 } },
        },
        ["vengeance"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 648, haste = 1156, mastery = 374, versatility = 327 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/raid/overview/mythic/all-bosses", targets = { crit = 702, haste = 1082, mastery = 481, versatility = 245 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/demon-hunter/vengeance/3v3", targets = { crit = 18, haste = 402, mastery = 808, versatility = 677 } },
        },
    },
    ["DRUID"] = {
        ["balance"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 768, haste = 795, mastery = 955, versatility = 122 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/raid/overview/mythic/all-bosses", targets = { crit = 802, haste = 728, mastery = 1022, versatility = 118 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/druid/balance/3v3", targets = { crit = 15, haste = 802, mastery = 178, versatility = 931 } },
        },
        ["feral"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 533, haste = 838, mastery = 1175, versatility = 107 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/raid/overview/mythic/all-bosses", targets = { crit = 574, haste = 821, mastery = 1000, versatility = 172 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/druid/feral/3v3", targets = { crit = 21, haste = 233, mastery = 661, versatility = 1004 } },
        },
        ["guardian"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 377, haste = 1261, mastery = 388, versatility = 679 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/raid/overview/mythic/all-bosses", targets = { crit = 367, haste = 1168, mastery = 487, versatility = 516 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/druid/guardian/3v3", targets = { crit = 96, haste = 757, mastery = 404, versatility = 734 } },
        },
        ["restoration"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 144, haste = 1170, mastery = 1035, versatility = 219 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/raid/overview/mythic/all-bosses", targets = { crit = 164, haste = 1239, mastery = 1126, versatility = 150 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/druid/restoration/3v3", targets = { crit = 12, haste = 348, mastery = 840, versatility = 689 } },
        },
    },
    ["EVOKER"] = {
        ["augmentation"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1298, haste = 978, mastery = 183, versatility = 65 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/raid/overview/mythic/all-bosses", targets = { crit = 1306, haste = 897, mastery = 260, versatility = 82 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/evoker/augmentation/3v3", targets = { crit = 123, haste = 915, mastery = 68, versatility = 806 } },
        },
        ["devastation"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1211, haste = 795, mastery = 445, versatility = 83 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/raid/overview/mythic/all-bosses", targets = { crit = 1214, haste = 818, mastery = 447, versatility = 97 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/evoker/devastation/3v3", targets = { crit = 121, haste = 444, mastery = 488, versatility = 884 } },
        },
        ["preservation"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 627, haste = 867, mastery = 827, versatility = 230 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/raid/overview/mythic/all-bosses", targets = { crit = 837, haste = 495, mastery = 1289, versatility = 97 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/evoker/preservation/3v3", targets = { crit = 107, haste = 726, mastery = 227, versatility = 859 } },
        },
    },
    ["HUNTER"] = {
        ["beast-mastery"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1223, haste = 301, mastery = 1057, versatility = 96 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/raid/overview/mythic/all-bosses", targets = { crit = 1034, haste = 485, mastery = 1053, versatility = 82 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/hunter/beast-mastery/3v3", targets = { crit = 36, haste = 170, mastery = 747, versatility = 970 } },
        },
        ["marksmanship"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1295, haste = 404, mastery = 760, versatility = 135 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/raid/overview/mythic/all-bosses", targets = { crit = 1360, haste = 420, mastery = 851, versatility = 103 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/hunter/marksmanship/3v3", targets = { crit = 37, haste = 134, mastery = 787, versatility = 935 } },
        },
        ["survival"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 830, haste = 600, mastery = 1234, versatility = 75 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/raid/overview/mythic/all-bosses", targets = { crit = 829, haste = 606, mastery = 1242, versatility = 78 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/hunter/survival/3v3", targets = { crit = 70, haste = 360, mastery = 754, versatility = 770 } },
        },
    },
    ["MAGE"] = {
        ["arcane"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 832, haste = 576, mastery = 940, versatility = 227 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/raid/overview/mythic/all-bosses", targets = { crit = 858, haste = 626, mastery = 901, versatility = 218 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/mage/arcane/3v3", targets = { crit = 16, haste = 714, mastery = 224, versatility = 956 } },
        },
        ["fire"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 103, haste = 1186, mastery = 1073, versatility = 146 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/raid/overview/mythic/all-bosses", targets = { crit = 150, haste = 1268, mastery = 1002, versatility = 135 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/mage/fire/3v3", targets = { crit = 43, haste = 811, mastery = 46, versatility = 1029 } },
        },
        ["frost"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1080, haste = 571, mastery = 938, versatility = 103 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/raid/overview/mythic/all-bosses", targets = { crit = 1062, haste = 588, mastery = 923, versatility = 80 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/mage/frost/3v3", targets = { crit = 2, haste = 846, mastery = 65, versatility = 1048 } },
        },
    },
    ["MONK"] = {
        ["brewmaster"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1130, haste = 232, mastery = 481, versatility = 755 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/raid/overview/mythic/all-bosses", targets = { crit = 1214, haste = 307, mastery = 442, versatility = 639 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/monk/brewmaster/3v3", targets = { crit = 116, haste = 272, mastery = 581, versatility = 998 } },
        },
        ["mistweaver"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 832, haste = 1141, mastery = 156, versatility = 470 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/raid/overview/mythic/all-bosses", targets = { crit = 933, haste = 1222, mastery = 216, versatility = 213 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/monk/mistweaver/3v3", targets = { crit = 35, haste = 769, mastery = 58, versatility = 1049 } },
        },
        ["windwalker"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 787, haste = 919, mastery = 765, versatility = 133 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/raid/overview/mythic/all-bosses", targets = { crit = 826, haste = 925, mastery = 748, versatility = 137 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/monk/windwalker/3v3", targets = { crit = 104, haste = 78, mastery = 946, versatility = 768 } },
        },
    },
    ["PALADIN"] = {
        ["holy"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 388, haste = 960, mastery = 903, versatility = 295 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/raid/overview/mythic/all-bosses", targets = { crit = 472, haste = 860, mastery = 1188, versatility = 124 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/paladin/holy/3v3", targets = { crit = 11, haste = 134, mastery = 690, versatility = 1063 } },
        },
        ["protection"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 898, haste = 1011, mastery = 389, versatility = 212 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/raid/overview/mythic/all-bosses", targets = { crit = 781, haste = 1024, mastery = 534, versatility = 219 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/paladin/protection/3v3", targets = { crit = 93, haste = 271, mastery = 625, versatility = 965 } },
        },
        ["retribution"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 966, haste = 601, mastery = 997, versatility = 69 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/raid/overview/mythic/all-bosses", targets = { crit = 916, haste = 632, mastery = 1023, versatility = 70 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/paladin/retribution/3v3", targets = { crit = 10, haste = 115, mastery = 600, versatility = 1237 } },
        },
    },
    ["PRIEST"] = {
        ["discipline"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 880, haste = 841, mastery = 805, versatility = 102 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/raid/overview/mythic/all-bosses", targets = { crit = 885, haste = 1007, mastery = 608, versatility = 95 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/priest/discipline/3v3", targets = { crit = 11, haste = 546, mastery = 541, versatility = 794 } },
        },
        ["holy"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 843, haste = 796, mastery = 352, versatility = 460 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/raid/overview/mythic/all-bosses", targets = { crit = 1082, haste = 555, mastery = 762, versatility = 176 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/priest/holy/3v3", targets = { crit = 9, haste = 336, mastery = 668, versatility = 879 } },
        },
        ["shadow"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 638, haste = 1049, mastery = 864, versatility = 71 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/raid/overview/mythic/all-bosses", targets = { crit = 562, haste = 1024, mastery = 974, versatility = 71 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/priest/shadow/3v3", targets = { crit = 39, haste = 873, mastery = 158, versatility = 861 } },
        },
    },
    ["ROGUE"] = {
        ["assassination"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1238, haste = 722, mastery = 527, versatility = 85 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/raid/overview/mythic/all-bosses", targets = { crit = 1213, haste = 715, mastery = 517, versatility = 109 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/rogue/assassination/3v3", targets = { crit = 73, haste = 152, mastery = 827, versatility = 856 } },
        },
        ["outlaw"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1344, haste = 923, mastery = 289, versatility = 171 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/raid/overview/mythic/all-bosses", targets = { crit = 1252, haste = 879, mastery = 285, versatility = 183 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/rogue/outlaw/3v3", targets = { crit = 84, haste = 644, mastery = 64, versatility = 1130 } },
        },
        ["subtlety"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 646, haste = 634, mastery = 1209, versatility = 69 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/raid/overview/mythic/all-bosses", targets = { crit = 722, haste = 698, mastery = 1088, versatility = 84 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/rogue/subtlety/3v3", targets = { crit = 74, haste = 168, mastery = 835, versatility = 816 } },
        },
    },
    ["SHAMAN"] = {
        ["elemental"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 914, haste = 448, mastery = 1128, versatility = 78 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/raid/overview/mythic/all-bosses", targets = { crit = 902, haste = 476, mastery = 1124, versatility = 89 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/shaman/elemental/3v3", targets = { crit = 87, haste = 699, mastery = 156, versatility = 984 } },
        },
        ["enhancement"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 460, haste = 980, mastery = 1092, versatility = 61 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/raid/overview/mythic/all-bosses", targets = { crit = 394, haste = 976, mastery = 1132, versatility = 79 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/shaman/enhancement/3v3", targets = { crit = 32, haste = 659, mastery = 162, versatility = 1067 } },
        },
        ["restoration"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1065, haste = 500, mastery = 298, versatility = 633 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/raid/overview/mythic/all-bosses", targets = { crit = 1203, haste = 461, mastery = 410, versatility = 435 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/shaman/restoration/3v3", targets = { crit = 106, haste = 306, mastery = 764, versatility = 750 } },
        },
    },
    ["WARLOCK"] = {
        ["affliction"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 987, haste = 940, mastery = 565, versatility = 111 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/raid/overview/mythic/all-bosses", targets = { crit = 1025, haste = 912, mastery = 568, versatility = 97 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/warlock/affliction/3v3", targets = { crit = 13, haste = 798, mastery = 89, versatility = 1031 } },
        },
        ["demonology"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1150, haste = 803, mastery = 606, versatility = 81 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/raid/overview/mythic/all-bosses", targets = { crit = 1135, haste = 826, mastery = 568, versatility = 80 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/warlock/demonology/3v3", targets = { crit = 22, haste = 774, mastery = 81, versatility = 1044 } },
        },
        ["destruction"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 974, haste = 881, mastery = 632, versatility = 113 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/raid/overview/mythic/all-bosses", targets = { crit = 1028, haste = 865, mastery = 650, versatility = 86 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/warlock/destruction/3v3", targets = { crit = 17, haste = 797, mastery = 116, versatility = 968 } },
        },
    },
    ["WARRIOR"] = {
        ["arms"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 1193, haste = 1023, mastery = 382, versatility = 52 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/raid/overview/mythic/all-bosses", targets = { crit = 1154, haste = 1009, mastery = 372, versatility = 68 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/warrior/arms/3v3", targets = { crit = 8, haste = 561, mastery = 186, versatility = 1172 } },
        },
        ["fury"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 545, haste = 1079, mastery = 1093, versatility = 74 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/raid/overview/mythic/all-bosses", targets = { crit = 509, haste = 1097, mastery = 1128, versatility = 77 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/warrior/fury/3v3", targets = { crit = 10, haste = 500, mastery = 408, versatility = 1165 } },
        },
        ["protection"] = {
            ["Mythic+"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week", targets = { crit = 551, haste = 1159, mastery = 427, versatility = 235 } },
            ["Raid"] = { source = "Archon", sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/raid/overview/mythic/all-bosses", targets = { crit = 680, haste = 1141, mastery = 496, versatility = 175 } },
            ["PvP"] = { source = "Murlok", sourceUrl = "https://murlok.io/warrior/protection/3v3", targets = { crit = 4, haste = 642, mastery = 209, versatility = 1077 } },
        },
    },
}

ZoidsToolsStatTargets = ZoidsToolsStatGoals.data
